### ISSUE TITLE
Installation Docs

### ISSUE THREAD

**Issue by una** [DesignOpen/ResourceCollectorChromeExtension#1]
:) How does one get started?

**Comment by cmata23x3** [comment]
@una Quick response would be to install the extension from the Chrome Web Store, which can be found [here](https://chrome.google.com/webstore/detail/design-open/jahbclkpigpnoeamhgdilpdocgicnmml). @lauweijie will update the README sometime soonish(?)

**Comment by lauweijie** [comment]
In the process of updating it!
